# Generated by Django 2.0.6 on 2018-06-04 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(help_text='gender; Enetr, (m) Male, (f) Female, (u) Unknown', max_length=1)),
                ('size', models.CharField(help_text='size; Enter, (s) Small, (m) Medium, (l) Large, (xl) Extra Large', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='status; Enter,  (l) Liked, (d) Disliked', max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(help_text='age; Enter, (b) Baby, (y) Young, (a) Adult, (s) Senior or a combaination seperated by a comma.', max_length=5)),
                ('gender', models.CharField(help_text='gender; Enter, (m) Male, (f) Female, (s) Senior or a combaination seperated by a comma.', max_length=4)),
                ('size', models.CharField(help_text='size; Enter, (s) Small, (m) Medium, (l) Large, (xl) Extra Large or a combination seperated by a comma.', max_length=6)),
                ('user', models.OneToOneField(help_text='Can only have one set of prefrences per user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
