# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20180606_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(help_text='age; Enter, (b) Baby, (y) Young, (a) Adult, (s) Senior or a combaination seperated by a comma.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(help_text='gender; Enter, (m) Male, (f) Female, (s) Senior or a combaination seperated by a comma.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(help_text='size; Enter, (s) Small, (m) Medium, (l) Large, (xl) Extra Large or a combination seperated by a comma.', max_length=10),
        ),
    ]
